# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TR0weR61LihjnT_HI5lq97TS_AZtkDOB
"""

usuario = "admin"
senha = "123"

for tentativa in range(5):
  usuario = input("login: ")
  senha = input("senha: ")
  if usuario == "admin" and senha == "123":
    print ("login concedido! ")
    break
  else:
    print("Tente novamente")